### ISSUE TITLE
Wordpress crashes after activating plugin

### ISSUE THREAD

**Issue by johhansantana** [wp-graphql/wp-graphql#315]
Just installed a clean Wordpress v4.9 locally after uploading the zip and activating the plugin I get the following error.

```
Warning: require(/Users/jsantana/Downloads/wordpress/wp-content/plugins/wp-graphql-develop/vendor/composer/../tracy/tracy/src/shortcuts.php): failed to open stream: No such file or directory in /Users/jsantana/Downloads/wordpress/wp-content/plugins/wp-graphql-develop/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/Users/jsantana/Downloads/wordpress/wp-content/plugins/wp-graphql-develop/vendor/composer/../tracy/tracy/src/shortcuts.php' (include_path='.:') in /Users/jsantana/Downloads/wordpress/wp-content/plugins/wp-graphql-develop/vendor/composer/autoload_real.php on line 66
```

Now I can't browser the Wordpress site.

**Comment by jasonbahl** [comment]
Try making the plugin directory `wp-graphql` instead of `wp-graphql-develop` and see if that helps? Also, can you verify that there is a `/vendor/composer/` directory in the plugin?

**Comment by johhansantana** [comment]
renamed it to `wp-graphql` still the same error.

The directory is there.

![wordpressgql](https://user-images.githubusercontent.com/9933887/32899983-d7062c2c-ca98-11e7-9612-a3aa4ff04610.gif)

**Comment by jasonbahl** [comment]
The screen recording helps a lot. Thanks! Let me see what I can find out

**Comment by jasonbahl** [comment]
I have been messing with composer stuff for unit tests so perhaps something I did had an unintended/unnoticed side-effect. I’ll get it straightened out shortly. Thanks!

**Comment by johhansantana** [comment]
awesome!, just saw the graphql summit video yesterday and I want to try it out with WordPress and see how it goes!

**Comment by jasonbahl** [comment]
In the mean time try the latest release/master branch while I fix develop

**Comment by jasonbahl** [comment]
@johhansantana just merged some changes. Can you confirm it's working for you now (develop branch)?

**Comment by johhansantana** [comment]
@jasonbahl seems to not be crashing now.

Though I can't query the `/graphql` endpoint:
![image](https://user-images.githubusercontent.com/9933887/32902326-94a58d4a-ca9e-11e7-91fa-9c40303aef54.png)

**Comment by jasonbahl** [comment]
@johhansantana what does your query look like? Are you using GraphiQL to test things?

**Comment by johhansantana** [comment]
I'm using a chrome app called Altair which is like the graphiql software:
![image](https://user-images.githubusercontent.com/9933887/32902865-ff4c6604-ca9f-11e7-881a-43a5ef07d2a0.png)

When I try to setup the url for the `/graphql` endpoint it just shows an error and when I check the console where wordpress is running I get the screen shot from before.

Sorry for the mess, I'm really a noob when it comes to working with wordpress.

**Comment by jasonbahl** [comment]
@johhansantana Never heard of Altair. Looks interesting! I just tried it out with the most recent version of the develop branch active and it looks like it's working for me 🤔 

![screen shot 2017-11-16 at 9 40 29 am](https://user-images.githubusercontent.com/1260765/32903565-8b530bd2-cab2-11e7-83bf-1e423b71eedd.png)

Curious if something with running it via `wp server` is causing issues. . .haven't tried testing it with that setup. 

Can you try on a more "normal" WP install and see if we can determine if using `wp server` is the culprit? Like maybe try Local by Flywheel or something like that?

**Comment by johhansantana** [comment]
🤔 I will try using Local by Flywheel, I don't have reliable internet right now to download a big file but when I do I'll test it.

I think the main topic for this issue has been resolved, maybe we can close and open another issue later when I get the chance to continue testing?

**Comment by jasonbahl** [comment]
@johhansantana sounds good! Also, what PHP version are you running?

**Comment by johhansantana** [comment]
when I do `php -v` I get
![image](https://user-images.githubusercontent.com/9933887/32904673-59dbb2ce-caa4-11e7-9a2e-ddc0a07e383b.png)

**Comment by imolorhe** [comment]
Altair! 🙌 😄

**Comment by paulonova** [comment]
Hi! We are in 2022 now and the plugin still not working!  Have you any suggestion to make it work?

**Comment by jasonbahl** [comment]
@paulonova we have more than 20,000 active users. The plugin works fine. 

Can you provide steps to reproduce how you are getting to a point where things crash?

**Comment by paulonova** [comment]
Hi!
Thanks for you feedback..

What is happening is:

1 - I install the plugin
2 - When I try to activate the plugin this message appears:


Is there something you can help me?

Best regards

Paulo

Den tis 1 nov. 2022 kl 15:47 skrev Jason Bahl ***@***.***>:

**Comment by justlevine** [comment]
@paulonova , you forgot (or your email client filtered out) the error message for (2) 😇

Regardless, please create a [new bug report](https://github.com/wp-graphql/wp-graphql/issues/new?assignees=&labels=&template=bug_report.yml), and include **all** the required information, including the steps to replicate (e.g. including where you're installing the plugin from, what version you're running, and confirmation that other plugins arent causing a conflict), which we need to diagnose / solve the specific problem you're having.

**Comment by paulonova** [comment]
Done!

Den ons 2 nov. 2022 kl 14:18 skrev Dovid Levine ***@***.***>:
