### ISSUE TITLE
Sizes attribute wrong

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#871]
Using the `sizes` attribute seems to always be too small. If I had to guess, it's not respecting the size that is passed in. 

`FULLSCREEN` in this example is `add_image_size( 'fullscreen', 1920, 1080, false )`

Query:
```
    sourceUrl(size: FULLSCREEN)
    sizes(size: FULLSCREEN)
    srcSet(size: FULLSCREEN)   
```

Output:
```
<img 
src="http://mpc2019.flywheelsites.com/wp-content/uploads/2019/04/Fischerspooner-Butterscotch-Goddamn4.jpg" 

srcset="http://mpc2019.flywheelsites.com/wp-content/uploads/2019/04/Fischerspooner-Butterscotch-Goddamn4-300x169.jpg 300w, http://mpc2019.flywheelsites.com/wp-content/uploads/2019/04/Fischerspooner-Butterscotch-Goddamn4-768x432.jpg 768w, http://mpc2019.flywheelsites.com/wp-content/uploads/2019/04/Fischerspooner-Butterscotch-Goddamn4-960x540.jpg 960w, http://mpc2019.flywheelsites.com/wp-content/uploads/2019/04/Fischerspooner-Butterscotch-Goddamn4-640x360.jpg 640w, http://mpc2019.flywheelsites.com/wp-content/uploads/2019/04/Fischerspooner-Butterscotch-Goddamn4.jpg 1000w" 

sizes="(max-width: 300px) 100vw, 300px"  // I think this should have a lot more in it
>
```

**Comment by drewbaker** [comment]
@kidunot89 and @jasonbahl I'm seeing `sizes` come in as `null` in 0.3.5

**Comment by craigwilcox** [comment]
Hi Jason and Ryan and All,

I noticed Ryan is asking for "needs to be reproduced".

I'm having this issue as well. The Wordpress sizes output for my particular image is: "sizes": "(max-width: 1980px) 100vw, 1980px". 

The WPGraphQL output is: "sizes": "(max-width: 300px) 100vw, 300px".

This happens both with using the Featured Image on WPGraphQL and with WPGraphQL ACF.

Thanks!
Craig

**Comment by colbyfayock** [comment]
I'm hitting this issue as well. Here's an example:

https://next-wordpress-starter.netlify.app/posts/voluptas-in-nemo-eaque-tempora-sit-quisquam/

In the code, I'm simply dumping the srcset and sizes attributes right into the image, resulting in this for this particular image:

```
<img width="100%" height="auto" src="https://i1.wp.com/54.243.240.9/wp-content/uploads/2020/10/photo-1502134249126-9f3755a50d78-scaled.jpeg?fit=2560%2C1707" alt="" srcset="https://i1.wp.com/54.243.240.9/wp-content/uploads/2020/10/photo-1502134249126-9f3755a50d78-scaled.jpeg?w=2560 2560w, https://i1.wp.com/54.243.240.9/wp-content/uploads/2020/10/photo-1502134249126-9f3755a50d78-scaled.jpeg?resize=300%2C200 300w, https://i1.wp.com/54.243.240.9/wp-content/uploads/2020/10/photo-1502134249126-9f3755a50d78-scaled.jpeg?resize=1024%2C683 1024w, https://i1.wp.com/54.243.240.9/wp-content/uploads/2020/10/photo-1502134249126-9f3755a50d78-scaled.jpeg?resize=768%2C512 768w, https://i1.wp.com/54.243.240.9/wp-content/uploads/2020/10/photo-1502134249126-9f3755a50d78-scaled.jpeg?resize=1536%2C1024 1536w, https://i1.wp.com/54.243.240.9/wp-content/uploads/2020/10/photo-1502134249126-9f3755a50d78-scaled.jpeg?resize=2048%2C1365 2048w, https://i1.wp.com/54.243.240.9/wp-content/uploads/2020/10/photo-1502134249126-9f3755a50d78-scaled.jpeg?resize=1200%2C800 1200w, https://i1.wp.com/54.243.240.9/wp-content/uploads/2020/10/photo-1502134249126-9f3755a50d78-scaled.jpeg?resize=1980%2C1320 1980w, https://i1.wp.com/54.243.240.9/wp-content/uploads/2020/10/photo-1502134249126-9f3755a50d78-scaled.jpeg?w=1740 1740w" sizes="(max-width: 300px) 100vw, 300px">
```

Here's a trace of the code for the above:

* Query: https://github.com/colbyfayock/next-wordpress-starter/blob/master/src/data/posts.js#L34
* Passed into display: https://github.com/colbyfayock/next-wordpress-starter/blob/master/src/pages/posts/%5Bslug%5D.js#L46
* Which ultimately ends up "as is" on the `img`: https://github.com/colbyfayock/next-wordpress-starter/blob/master/src/components/Image/Image.js#L23

^ AKA nothing special is going on with the srcset or sizes attributes

let me know if I can help debug or something

**Comment by colbyfayock** [comment]
any thoughts on what this could be?

**Comment by drewbaker** [comment]
I think we fixed this with this PR: https://github.com/wp-graphql/wp-graphql/pull/1760

But I’m not sure if that is in a current release yet?

**Comment by colbyfayock** [comment]
cool thanks @drewbaker i'll keep an eye out for that

**Comment by bhardie** [comment]
Closed by #1760

**Comment by colbyfayock** [comment]
would it be possible to get a bit of clarification on the versionining for that fix? it looks like it was merged into 1.2.6, as opposed to 1.3.X

i addmittedly don't completely understand how the responsive images work, but im still seeing the same thing i was before on 1.3.5, but guessing it's either because it wasn't merged into 1.3 or its not the issue im seeing

![image](https://user-images.githubusercontent.com/1045274/115944532-52feca00-a484-11eb-8ff6-348259c1252d.png)

**Comment by drewbaker** [comment]
What’s the GQL you used to generate that. I found that you need to do sizes(size: LARGEST_SIZE_HERE) for it to give you all sizes. 

https://github.com/funkhaus/fuxt/blob/master/gql/fragments/MediaImage.gql

**Comment by colbyfayock** [comment]
here's the query I used for the above:
```
query MyQuery {
  posts {
    edges {
      node {
        featuredImage {
          node {
            sizes
            srcSet
          }
        }
      }
    }
  }
}

```

i dont have any custom sizes set up but heres hwat i get when i try to set using `LARGE`

![image](https://user-images.githubusercontent.com/1045274/115975786-de846380-a535-11eb-87d1-a3025865ffa9.png)


i looks like the property changed, but i dont get all of them, shouldnt sizes have multiple queries in there?

**Comment by drewbaker** [comment]
Looks like `large` is only 580px wide. And all your images are bigger than that. Try it with `FULL` as the size.

**Comment by colbyfayock** [comment]
i dont have `FULL` available :(
